local path = "aidenwen.plugins."
require(path.. "lazy")
require(path.. "telescope")
require(path.. "treesitter")
require(path.. "gitsigns")
require(path.. "autoclose")
require(path.. "lsp")
require(path.. "theme")
require(path.. "netrw")
require(path.. "debugger")
